<?php

namespace AppBundle\Repository;

/**
 * educformRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class educformRepository extends \Doctrine\ORM\EntityRepository
{
}
