<?php

namespace AppBundle\Repository;

/**
 * facultyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacultyRepository extends \Doctrine\ORM\EntityRepository
{
}
