<?php

namespace AppBundle\Repository;

/**
 * rankRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class rankRepository extends \Doctrine\ORM\EntityRepository
{
}
