<?php

namespace AppBundle\Repository;

/**
 * roomtypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class roomtypeRepository extends \Doctrine\ORM\EntityRepository
{
}
