<?php

namespace AppBundle\Repository;

/**
 * toomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class toomRepository extends \Doctrine\ORM\EntityRepository
{
}
