<?php

namespace AppBundle\Repository;

/**
 * semesterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class semesterRepository extends \Doctrine\ORM\EntityRepository
{
}
