<?php

namespace AppBundle\Repository;

/**
 * specialityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class specialityRepository extends \Doctrine\ORM\EntityRepository
{
}
