<?php

namespace AppBundle\Repository;

/**
 * groupsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudyGroupsRepository extends \Doctrine\ORM\EntityRepository
{
}
