<?php

namespace AppBundle\Repository;

/**
 * subfacultyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubfacultyRepository extends \Doctrine\ORM\EntityRepository
{
}
