<?php

namespace AppBundle\Repository;

/**
 * typelectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class typelectRepository extends \Doctrine\ORM\EntityRepository
{
}
