<?php

namespace AppBundle\Repository;

/**
 * typelessonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypelessonRepository extends \Doctrine\ORM\EntityRepository
{
}
