AppBundle\Entity\Timetable:
    exclusion_policy: all
    properties:
        begindatetime:
            expose: true
        studygroup:
            expose: true
        room:
            expose: true
        teacher:
            expose: true
        typelesson:
            expose: true
#        semester:
#            expose: false